### ISSUE TITLE
NeSS documents not opening.

### ISSUE THREAD

**Issue by gnaneswar-k** [IIITH-Resources/NeSS#5]
Below documents aren't opening. We're being redirected to the error page.

Pages:
1. Assignments
2. Exams

![Screenshot_20220119-160001_Chrome](https://user-images.githubusercontent.com/97674245/150112844-5fb9fa6a-3ff8-470b-9f6f-d4acfbd33cf4.jpg)

![Screenshot_20220119-160157_Chrome](https://user-images.githubusercontent.com/97674245/150113411-00a870e5-7515-4b2e-a623-71963118a389.jpg)

**Comment by ghost** [comment]
They are opening as far as I can see

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/77191936/150272913-a2eb5941-46ff-4a6e-8c1a-7513e8734952.png)

**Comment by gnaneswar-k** [comment]
For me it still is showing the error page in Android

**Comment by gnaneswar-k** [comment]
https://iiith-resources.github.io/Networks_Signals_and_Systems/Web/exam.html

This is the website right?

**Comment by ghost** [comment]
Yes, the website is right

**Comment by ghost** [comment]
Does the click here button work ?

**Comment by gnaneswar-k** [comment]
Yep click here works, but in actual website it isn't displaying

**Comment by bhavberi** [comment]
Once try opening in private tab, and also mention which device are you using.

**Comment by gnaneswar-k** [comment]
The issue still persists even in Incognito, both before and after clearing the cache. I checked in the following devices and browsers:

motorola edge 20 pro
Android 11
Browser:
Google Chrome v97.0.4692.87

Samsung Galaxy Tab A 10.5 (2018)
Android 10
Browsers:
Google Chrome v96.0.4664.104
Samsung Internet v16.0.6.23

**Comment by bhavberi** [comment]
Ok
I have made some changes, after 5 mins check once in private window.
Hope it works now.

**Comment by bhavberi** [comment]
Thanks @gnaneswar-k for the issue.
